kind: ConfigMap
apiVersion: v1
metadata:
  name: orchestrator-config
data:
  config.yaml: |
    chat_generation:
      service:
        hostname: qwen3-14b-llm-metrics.incub-deploy.svc.cluster.local
        port: 8080
    detectors:
      regex_competitor:    #built_in:
        type: text_contents
        service:
            hostname: "127.0.0.1"
            port: 8080
        chunker_id: whole_doc_chunker
        default_threshold: 0.5
      hap:
        type: text_contents
        service:
          hostname: guardrails-detector-ibm-hap-predictor.incub-deploy.svc.cluster.local
          port: 80
        chunker_id: whole_doc_chunker
        default_threshold: 0.5