apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: moj
resources:
  - ./1-hap-model-container.yaml
  - ./2-hap.yaml
  - ./3-configmap_vllm_gateway.yaml
  - ./4-configmap_auxiliary_images.yaml
  - ./5-configmap_orchestrator.yaml
  - ./6-gateway_route.yaml
  - ./7-orchestrator_cr.yaml





