apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: search-app
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/moj-incub-auth/moj-vector-data.git
    targetRevision: main
    path: 'deploy/openshift/deployment'
  destination:
    name: in-cluster
    namespace: 'moj-vector-data'
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true