apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: moj
resources:
  - ./deploy-search-app.yaml
  - ./deploy-tasks.yaml
  - ./deploy-vibe-ui.yaml
  #- ./deploy-pipelines.yaml
  #- ./deploy-webhooks.yaml




