apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: incub-deploy
  namespace: incub-deploy
spec:
  project: moj-incub-deploy
  source:
    repoURL: https://github.com/moj-incub-auth/moj-gitops.git
    targetRevision: main
    path: 'deployment/overlays/deploy'
  destination:
    name: in-cluster
  #server: https://kubernetes.default.svc
    namespace: 'incub-deploy'
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true
