apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: moj
resources:
  - ./deploy-tasks.yaml
  - ./deploy-pipelines.yaml
  - ./deploy-webhooks.yaml
  - ./deploy-task-ai.yaml




